package com.diltheyaislan.hibernateoracle;
// Generated 29 de set. de 2021 18:52:43 by Hibernate Tools 5.5.3.Final

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String cpf;
	private String nome;
	private String email;

	public Cliente() {
	}

	public Cliente(String cpf, String nome) {
		this.cpf = cpf;
		this.nome = nome;
	}

	public Cliente(String cpf, String nome, String email) {
		this.cpf = cpf;
		this.nome = nome;
		this.email = email;
	}

	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public String toString() {
		return "Cliente [cpf=" + cpf + ", nome=" + nome + ", email=" + email + "]";
	}
}
