package com.diltheyaislan.hibernateoracle;
// Generated 29 de set. de 2021 18:52:43 by Hibernate Tools 5.5.3.Final

import java.math.BigInteger;

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private BigInteger cdcurso;
	private String nome;
	private BigInteger valor;
	private String url;

	public Curso() {
	}

	public Curso(BigInteger cdcurso, String nome, BigInteger valor, String url) {
		this.cdcurso = cdcurso;
		this.nome = nome;
		this.valor = valor;
		this.url = url;
	}

	public BigInteger getCdcurso() {
		return this.cdcurso;
	}

	public void setCdcurso(BigInteger cdcurso) {
		this.cdcurso = cdcurso;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public BigInteger getValor() {
		return this.valor;
	}

	public void setValor(BigInteger valor) {
		this.valor = valor;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Override
	public String toString() {
		return "Curso [cdcurso=" + cdcurso + ", nome=" + nome + ", valor=" + valor + ", url=" + url + "]";
	}
}
