package com.diltheyaislan.hibernateoracle;
// Generated 29 de set. de 2021 18:52:43 by Hibernate Tools 5.5.3.Final

import java.util.Date;

/**
 * Pagamento generated by hbm2java
 */
public class Pagamento implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private PagamentoId id;
	private Date datainscricao;

	public Pagamento() {
	}

	public Pagamento(PagamentoId id, Date datainscricao) {
		this.id = id;
		this.datainscricao = datainscricao;
	}

	public PagamentoId getId() {
		return this.id;
	}

	public void setId(PagamentoId id) {
		this.id = id;
	}

	public Date getDatainscricao() {
		return this.datainscricao;
	}

	public void setDatainscricao(Date datainscricao) {
		this.datainscricao = datainscricao;
	}

	@Override
	public String toString() {
		return "Pagamento [id=" + id + ", datainscricao=" + datainscricao + "]";
	}
}
