package com.diltheyaislan.hibernateoracle;
// Generated 29 de set. de 2021 18:52:43 by Hibernate Tools 5.5.3.Final

import java.math.BigInteger;

/**
 * PagamentoId generated by hbm2java
 */
public class PagamentoId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private BigInteger cdcurso;
	private String cpf;

	public PagamentoId() {
	}

	public PagamentoId(BigInteger cdcurso, String cpf) {
		this.cdcurso = cdcurso;
		this.cpf = cpf;
	}

	public BigInteger getCdcurso() {
		return this.cdcurso;
	}

	public void setCdcurso(BigInteger cdcurso) {
		this.cdcurso = cdcurso;
	}

	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PagamentoId))
			return false;
		PagamentoId castOther = (PagamentoId) other;

		return ((this.getCdcurso() == castOther.getCdcurso()) || (this.getCdcurso() != null
				&& castOther.getCdcurso() != null && this.getCdcurso().equals(castOther.getCdcurso())))
				&& ((this.getCpf() == castOther.getCpf()) || (this.getCpf() != null && castOther.getCpf() != null
						&& this.getCpf().equals(castOther.getCpf())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCdcurso() == null ? 0 : this.getCdcurso().hashCode());
		result = 37 * result + (getCpf() == null ? 0 : this.getCpf().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "PagamentoId [cdcurso=" + cdcurso + ", cpf=" + cpf + "]";
	}
}
